[workspace]
authors = ["Chen Zhang <chenzhang8722@gmail.com>"]
channels = ["conda-forge"]
name = "all_venus_scripts"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12"
jupyterlab = ">=4.4.5,<5"
ipywidgets = ">=8.1.7,<9"
numpy = ">=2.3.2,<3"
matplotlib = ">=3.10.3,<4"
pandas = ">=2.3.1,<3"
h5py = ">=3.14.0,<4"
scikit-image = ">=0.25.2,<0.26"
lmfit = ">=1.3.4,<2"
pillow = ">=11.3.0,<12"

[pypi-dependencies]
neunorm = ">=1.6.12, <2"
